### ISSUE TITLE
Not found SSOResponse, SignInWithSSO

### ISSUE THREAD

**Issue by stevensu1977** [Proziam/supabase-auth-rs#1]
I try fork it and add some user meta field , but I'm not luck , get error 

 no `SSOResponse` , no `SignInWithSSO` in `models`

Am I missing something ?

**Comment by Proziam** [comment]
The SSO implementation is still unfinished. I have a lot more work done locally, but it's still untested, so I haven't pushed it yet. SSO is the last major piece before 1.0. 

At the moment, I'm waiting on a few things from the Supabase team before I can finalize the SSO API. I recommend checking back in 2-4 weeks; this crate should be much more stable by then.

**Comment by Proziam** [comment]
Fixed
