### ISSUE TITLE
[Feature] Sign Up with Third Party Auth (OAuth)

### ISSUE THREAD

**Issue by jonatino** [Proziam/supabase-auth-rs#8]
Looks like you already support sign in, do you also plan to support sign up?

**Comment by Proziam** [comment]
Somewhat counter-intuitively, since version 1, Supabase has allowed for OAuth registration using sign-in methods.

https://github.com/orgs/supabase/discussions/1226#discussioncomment-654568

It might be worthwhile adding a distinct method just to eliminate the potential confusion.

**Comment by jonatino** [comment]
@Proziam oh that is quite counter intuitive. Whether or not you want to add another sign-up method is up to you. It'd probably make sense to follow the js client 1:1 just so people won't expect any surprises. Thanks Eric!
